---
- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true

- name: Install Python boto3
  ansible.builtin.package:
    name: python3-boto3
    state: present
    update_cache: true

- name: Set qdisc
  ansible.posix.sysctl:
    name: net.core.default_qdisc
    value: fq
    sysctl_set: true
    state: present
    reload: true
  register: qdisc_result

- name: Set BBR
  ansible.posix.sysctl:
    name: net.ipv4.tcp_congestion_control
    value: bbr
    sysctl_set: true
    state: present
    reload: true
  when: qdisc_result is success

- name: Deploy haproxy.cfg
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0644"
    validate: haproxy -c -f %s
  notify: Restart haproxy service

- name: Ensure HAProxy is running
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true

- name: Ensure curl present
  ansible.builtin.package:
    name: curl
    state: present

- name: Install x-ui via script
  ansible.builtin.shell: |
    {{ xui_control_install_cmd }}
  args:
    executable: /bin/bash
    creates: /usr/local/x-ui
  changed_when: true
  notify: Restart haproxy service
